###consul服务端口号
server:
  port: 80

spring:
  application:
    name: cloud-order-service
  ####consul注册中心地址
  cloud:
    consul:
      host: 192.168.184.131
      port: 8500
      discovery:
        #从consul服务器找本服务访问的ip地址
        hostname: 192.168.1.102
        service-name: ${spring.application.name}